### ISSUE TITLE
Code autocomplete does not work on windows

### ISSUE THREAD

**Issue by vasily-kirichenko** [RustDT/RustDT#56] opened 2015-08-10 19:32 UTC
For code

``` rust
fn main() {
    let v = vec
}
```

where the caret is next to `vec` and I press `Ctrl+Space`, I get:

![image](https://cloud.githubusercontent.com/assets/873919/9181663/d1990f92-3fae-11e5-8b0a-a9c88a9eefcd.png)

If I press `Esc`, I get no suggestions:

![image](https://cloud.githubusercontent.com/assets/873919/9181685/f40bf512-3fae-11e5-87dc-2531ff820c48.png)

The settings look good:

![image](https://cloud.githubusercontent.com/assets/873919/9181746/5a349092-3faf-11e5-979d-bce5e43b6bfd.png)

Version:

![image](https://cloud.githubusercontent.com/assets/873919/9181784/8d6faf5a-3faf-11e5-8f28-b235eb38ad9b.png)

PS: Another error:

![image](https://cloud.githubusercontent.com/assets/873919/9181875/0b8c1acc-3fb0-11e5-9d1f-53faf4ccdad2.png)

**Comment by bruno-medeiros** [comment] 2015-08-11 11:33
The first error, "Unknown line format: END" has already been fixed in HEAD.

The second error, duplicate of  #47

**Closed as completed by bruno-medeiros** 2015-08-11 11:33 UTC

**Comment by bruno-medeiros** [comment] 2015-08-11 11:36
Ah forgot to mention, a workaround for the "Unknown line format: END" is to use a slightly older version of Racer, pre-1.0.0.
