### ISSUE TITLE
Editor Codefolding - Code Collapsing code blocks

### ISSUE THREAD

**Issue by b-pos465** [RustDT/RustDT#77] opened 2015-11-25 15:42 UTC
It would be nice to be able to collapse functions, structs, enum and impl blocks for a better overview :)

Great work so far!

**Comment by mxmind** [comment] 2016-01-20 15:49
I'm voting for this feature too

**Comment by bruno-medeiros** [comment] 2016-04-12 14:11
duplicate of #7

**Closed as completed by bruno-medeiros** 2016-04-12 14:11 UTC
Labels: enhancement
