### ISSUE TITLE
Avoid displaying dialogs for errors relating to auto-completion

### ISSUE THREAD

**Issue by Diggsey** [RustDT/RustDT#48] opened 2015-07-28 16:57 UTC
A problem with autocompletion shouldn't interrupt the programmer's typing - it's fine for errors to just show in the status bar.

**Comment by freeman42x** [comment] 2015-08-02 17:48
:+1: This would be really helpful as it breaks the flow of typing too many times. And disabling the autocomplete or setting a higher autocomplete timeout is not really that good of a solution.

**Comment by bruno-medeiros** [comment] 2015-08-03 14:32
Duplicate of #41

**Closed as completed by bruno-medeiros** 2015-08-03 14:32 UTC
